buildscript {
    repositories {
        //TODO: del this!
        mavenLocal()

        mavenCentral()
    }

    dependencies {
        classpath 'info.gianlucacosta.aurora:aurora:10.0.0-SNAPSHOT'
    }
}


apply plugin: 'java'
apply plugin: 'application'
apply plugin: 'info.gianlucacosta.aurora'


group 'info.gianlucacosta.historymark'
archivesBaseName = 'historymark'
version '2.0.0-SNAPSHOT'


sourceCompatibility = 1.8

description = 'Interactive Java app for historical events'

mainClassName = "info.gianlucacosta.historymark.App"


aurora {
    gitHubUser = 'giancosta86'

    author {
        name = 'Gianluca Costa'
        email = 'gianluca@gianlucacosta.info'
        url = 'http://gianlucacosta.info/'
    }
}


dependencies {
    compile 'info.gianlucacosta.atlas:atlas:2.0.0-SNAPSHOT'
    compile 'info.gianlucacosta.zephyros:zephyros-hibernate:2.0.0-SNAPSHOT'

    compile 'org.hsqldb:hsqldb:2.4.0'
    compile 'com.thoughtworks.xstream:xstream:1.4.10'

    testCompile 'junit:junit:4.12'
    testCompile 'org.hamcrest:hamcrest-all:1.3'
}
