buildscript {
    repositories {
        maven {
            url 'https://dl.bintray.com/giancosta86/Hephaestus'
        }

        jcenter()
    }

    dependencies {
        classpath 'info.gianlucacosta.moonlicense:moonlicense-gradle:5.0'
        classpath 'info.gianlucacosta.moondeploy:moondeploy-gradle:3.4'
        classpath 'info.gianlucacosta.aurora:aurora:9.2'
    }
}


apply plugin: 'java'
apply plugin: 'application'
apply plugin: 'info.gianlucacosta.moonlicense'
apply plugin: 'info.gianlucacosta.moondeploy'
apply plugin: 'info.gianlucacosta.aurora'


group 'info.gianlucacosta.historymark'
archivesBaseName = 'historymark'
version '1.1'


sourceCompatibility = 1.8

description = 'Interactive Java app for historical events'

project.ext.facebookPage = 'https://www.facebook.com/HistoryMark-122373171802409/'

mainClassName = "info.gianlucacosta.historymark.App"


aurora {
    gitHubUser = 'giancosta86'

    author {
        name = 'Gianluca Costa'
        email = 'gianluca@gianlucacosta.info'
        url = 'http://gianlucacosta.info/'
    }
}



moonLicense {
    license = apache2

    productInfo {
        productName = 'HistoryMark'
        inceptionYear = 2017
        copyrightHolder = 'Gianluca Costa'
    }

    excludes = [
            'WelcomeMessage\\.htm$'
    ]
}


dependencies {
    compile 'info.gianlucacosta.atlas:atlas:1.0'
    compile 'info.gianlucacosta.zephyros:zephyros-core:1.1'
    compile 'info.gianlucacosta.zephyros:zephyros-hibernate:1.0'

    compile 'org.hsqldb:hsqldb:2.4.0'
    compile 'com.thoughtworks.xstream:xstream:1.4.10'

    testCompile 'junit:junit:4.12'
    testCompile 'org.hamcrest:hamcrest-all:1.3'
}
